name: gsfast
channels:
  - pytorch
  - nvidia
  - pyg
  - conda-forge
  - defaults
dependencies:
  - plyfile=0.8.1
  - cudatoolkit=11.6
  - plyfile=0.8.1
  - python=3.8
  - pip=22.3.1
  - pytorch=1.12.1
  - torchaudio=0.12.1
  - torchvision=0.13.1
  - pytorch-scatter
  - tqdm
  - pip:
    - einops
    - wandb
    - lpips
    - laspy
    - jaxtyping
    - opencv-python
